### ISSUE TITLE
生产环境：缺少docker-compose.yml文件

### ISSUE THREAD

**Issue by xumuxi142857** [xerrors/Yuxi-Know#127]
您的readme中说部署环境时需要
`docker compose -f docker/docker-compose.yml --env-file src/.env up --build -d`
但是docker文件夹中并没有docker-compose.yml这个文件，只有docker-compose.dev.yml,请问是我哪里弄错了吗？感谢解答！

**Comment by xerrors** [comment]
不好意思，这部分描述忘记移除了。因为生产环境有时会出现问题，且目前个人开发者没额外的精力去验证实际生产环境中的表现以及 BUG，因此该源文件被移除了。

**Comment by xerrors** [comment]
这里可以参考之前的版本的文件：https://github.com/xerrors/Yuxi-Know/blob/1bf0af44dd163ca41d454c1c24c99a34de1f2eb4/docker/docker-compose.yml

其实主要的区别就在于 web 那里

```yml
 # 前端服务
  web:
    build:
      context: ..
      dockerfile: docker/web.Dockerfile
      target: production
    container_name: web-prod
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - app-network
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://api:8000  # 添加这行
```

以及 api 服务那里关闭了 --reload

```yml
api:
    build:
      context: ..
      dockerfile: docker/api.Dockerfile
    container_name: api-prod
    working_dir: /app
    volumes:
      - ../src:/app/src
      - ../saves:/app/saves
      - /hdd/zwj/models:/hdd/zwj/models
    ports:
      - "8000:8000"
    depends_on:
      - graph
      - milvus
    networks:
      - app-network
    environment:
      - NEO4J_URI=bolt://graph:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=0123456789
      - MILVUS_URI=http://milvus:19530
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000
```
