### ISSUE TITLE
Error: mac无法安装nvidia-container-toolkit，有什么办法可以正常运行呢

### ISSUE THREAD

**Issue by ZZTNB** [xerrors/Yuxi-Know#209]
1️⃣ 描述一下问题

2️⃣ 报错日志

请运行以下命令，并提供部分相关日志：

```sh
docker logs --tail=100 api-dev
```

3️⃣ 相关截图

#️⃣ 其他相关信息

✅ 如果问题与模型调用相关，请尝试切换到其他在线模型

**Comment by xerrors** [comment]
只需要修改现在的 docker-compose.yml，删除现有的 deploy 部分代码，但是需要注意的是，这样的话，就无法使用本地模型 [#209](https://github.com/xerrors/Yuxi-Know/issues/209)。

```yml
services:
  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    image: yuxi-api:0.1.0
    container_name: api-dev
    working_dir: /app
    volumes:
      - ./server:/app/server
      - ./src:/app/src
      - ./saves:/app/saves
      - ${MODEL_DIR:-./models}:/models  # 使用默认值处理未定义的环境变量
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           device_ids: ['1']
    #           capabilities: [gpu]
```

PS：如果是个人使用，而不是有开发需求的话，其他同类的开源项目可能更加合适一些，比如 cherrystudio、ragflow等等，都是非常优秀的 且适合个人使用的项目。
