### ISSUE TITLE
已经安装了nvidia-container-cli但api容器无法正常启动

### ISSUE THREAD

**Issue by Implacid** [xerrors/Yuxi-Know#211]
1️⃣ 描述一下问题

nvidia-container-cli已经正常安装，并且运行 sudo docker run --rm --gpus all nvidia/cuda:11.6.2-base-ubuntu20.04 nvidia-smi也返回正常，但是api容器一直无法启动。

2️⃣ 报错日志

Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running prestart hook #0: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: device error: 1: unknown device: unknown

3️⃣ 相关截图

![Image](https://github.com/user-attachments/assets/8cdc56eb-2712-449b-b28a-63fc888a8e62)

#️⃣ 其他相关信息

✅ 如果问题与模型调用相关，请尝试切换到其他在线模型

**Comment by xerrors** [comment]
这个是由于 docker-compose 文件中，默认配置的 GPU device id 是 1，如果设备只有一张显卡的话，就会出现这个问题，可以在文件中修改

```yml
services:
  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
      # args:
      #   http_proxy: http://172.19.13.5:7890
      #   https_proxy: http://172.19.13.5:7890
    image: yuxi-api:0.1.0
    container_name: api-dev
    working_dir: /app
    volumes:
      - ./server:/app/server
      - ./src:/app/src
      - ./saves:/app/saves
      - ${MODEL_DIR:-./models}:/models  # 使用默认值处理未定义的环境变量
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']  # 使用GPU 1  <<<<<<<<< 修改这里为 '0'
              capabilities: [gpu]
```
